### ISSUE TITLE
Review on SolarCalculator

### ISSUE THREAD

**Issue by Slimchux1** [hngi/Aeolus_SolarCalculator#31]
For the add appliance section, I think we should include others in case the said appliance is not included in the listed option.

**Comment by AndikanGabriel** [comment]
@Slimchux1 When talking of **others**, do you mean, a text field where a user can input an appliance name?

**Comment by Slimchux1** [comment]
Yes, that will be much better but we can still make use of a general option (others)

**Comment by AndikanGabriel** [comment]
> 
> 
> Yes, that will be much better but we can still make use of a general option (others)

Okay. That will be included

**Comment by Oluwablin** [comment]
Yes, it will much be better. Thanks for including it, Andy
