### ISSUE TITLE
Report on the background picture of the Solar Calculator sketch 

### ISSUE THREAD

**Issue by Oluwablin** [hngi/Aeolus_SolarCalculator#33]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Oluwablin** [comment]
Try and make the picture of that Solar Calculator template bigger and clearer. Also, the app has a logo, replace it with that S standing aimlessly on the landing page of the app

**Comment by AndikanGabriel** [comment]
@Oluwablin the logo at hand does not fit into the template design, however, a new logo will be released soon

**Comment by AndikanGabriel** [comment]
> 
> 
> Try and make the picture of that Solar Calculator template bigger and clearer. Also, the app has a logo, replace it with that S standing aimlessly on the landing page of the app

**Comment by Oluwablin** [comment]
@andygcodes no problem, quickly add it. Hope it comes in on time because we are to submit before 9am todau
